# Generated by Django 4.2 on 2025-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_question_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='order',
            new_name='display_order',
        ),
    ]
